source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

pod "PLMediaStreamingKit", :path => "../"


target 'PLMediaStreamingKitDemo' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Masonry'
  pod 'Queen', '2.0.0-official-pro'
end

target 'BroadcastUploadExtension' do
end

target 'BroadcastUploadExtensionSetupUI' do
end
